### PR TITLE
F/GitHub env var

### LINKED ISSUE #12: Adjust .travis.yml for Cake 2.x to include the GitHub ENV PRIVATE_KEY
Ref: https://github.com/FriendsOfCake/travis/issues/59#issuecomment-92382588

### PR DESCRIPTION
**Pull request by jtyost2**
Closes #12

### CODE REVIEW

**Comment by jtyost2** [comment]
Assigned @beporter to review.

@ricog you may want to look over the changes as well to see if you have any questions about how I described the GitHub token and it's role and such.

**Comment by jtyost2** [comment]
Bumping @beporter review, please.

**Comment by ricog** [comment]
Looks good assuming it needs write access or the `(no scope)` option didn't give you adequate permissions.

**Comment by beporter** [comment]
Agreed, it looks good to me.

Should we mention that you might need to run `gem install travis` before you can encrypt the token?

**Comment by jtyost2** [comment]
@ricog Tested the `no_scope` but no it doesn't provide the right access according to the documentation. https://developer.github.com/v3/oauth/#scopes

**Comment by jtyost2** [comment]
Yes, we should include the line about installing the gem.

Issue created to capture this and ensure I do it: #17

**Comment by jtyost2** [comment]
Added the line about installing the gem.

Reassigning to @beporter for final review.

**Comment by beporter** [comment]
Yep, looks good to me, but @jtyost2 I think you should be in charge of merging for the Plugin Skeleton. This is really your project.

Besides, I have enough review/merge responsibility already between the Shell Scripts, the normal Skeleton, the Puphpet stuff, ConfigRead, BasicSeeds....

You'll be able to go faster if you aren't waiting on me.

**Pull request merged**
